# Generated by Django 3.2.8 on 2021-11-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_brand', '0001_initial'),
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='eshop_brand.brand'),
            preserve_default=False,
        ),
    ]
