# Generated by Django 3.2.8 on 2021-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0002_remove_tag_products'),
        ('eshop_products', '0002_auto_20211101_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='eshop_tag.Tag'),
        ),
    ]
