# Generated by Django 3.2.8 on 2021-11-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_brand', '0003_auto_20211103_2251'),
        ('eshop_products', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_brand.brand'),
        ),
    ]
