# Generated by Django 3.2.8 on 2021-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0001_initial'),
        ('eshop_products', '0003_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='eshop_product_category.Category'),
        ),
    ]
