# Generated by Django 3.2.8 on 2021-11-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0004_auto_20211105_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
    ]
