# Generated by Django 3.2.8 on 2021-11-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0004_auto_20211101_2251'),
        ('eshop_products', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_product_category.category'),
        ),
    ]
