# Generated by Django 3.2.8 on 2021-11-05 23:19

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_image_gallery_path, verbose_name='تصویر'),
        ),
    ]
