# Generated by Django 3.2.8 on 2021-11-02 11:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0009_rename_slug_category_url'),
        ('eshop_products', '0010_auto_20211102_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_product_category.category'),
        ),
    ]
