# Generated by Django 3.2.8 on 2021-11-02 12:43

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0009_rename_slug_category_url'),
        ('eshop_products', '0012_auto_20211102_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, to='eshop_product_category.Category'),
        ),
    ]
