# Generated by Django 3.2.8 on 2021-11-03 00:19

from django.db import migrations, models
import django.db.models.deletion
import eshop_product_category.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(verbose_name='توضیحان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_product_category.models.upload_image_path, verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('url', models.CharField(max_length=120, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Tag', models.ManyToManyField(blank=True, to='eshop_tag.Tag')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop_product_category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
