# Generated by Django 3.2.8 on 2021-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0002_category_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
