# Generated by Django 3.2.8 on 2021-11-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0002_auto_20211103_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
