# Generated by Django 3.2.8 on 2021-11-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_remove_product_category'),
        ('eshop_product_category', '0004_auto_20211101_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
