# Generated by Django 3.2.8 on 2021-11-01 23:06

from django.db import migrations, models
import eshop_product_category.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0002_remove_tag_products'),
        ('eshop_product_category', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='eshop_tag.Tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0, verbose_name='توضیحان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_product_category.models.upload_image_path, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
