# Generated by Django 3.2.8 on 2021-11-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0007_auto_20211102_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
