# Generated by Django 3.2.8 on 2021-11-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120, verbose_name='نام برچسب'),
        ),
    ]
