# Generated by Django 3.2.8 on 2021-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about',
            field=models.TextField(default='درباره ما', verbose_name='درباره ما'),
        ),
    ]
