# Generated by Django 3.2.8 on 2021-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesettings_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='CopyRight',
            field=models.CharField(default=1, max_length=150, verbose_name='کپی رایت سایت'),
            preserve_default=False,
        ),
    ]
