# Generated by Django 3.2.8 on 2021-11-06 20:53

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_sitesettings_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map',
            field=models.ImageField(blank=True, default='', upload_to=eshop_settings.models.upload_image_path),
        ),
    ]
