# Generated by Django 3.2.8 on 2021-11-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_brand', '0002_brand_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(max_length=120, verbose_name='ادرس در url'),
        ),
    ]
