# Generated by Django 3.2.8 on 2021-11-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان پیام')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟/نشده')),
            ],
        ),
    ]
