# Generated by Django 3.2.8 on 2021-11-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس باما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
    ]
